---
- name: check if .emacs.d already cloned
  sudo: yes
  sudo_user: "{{remote_user}}"
  stat: path=~/.emacs.d
  register: emacs_config_path
  changed_when: False

- name: clone .emacs.d
  sudo: yes
  sudo_user: "{{remote_user}}"
  git: >-
    repo=git@github.com:tmtxt/.emacs.d.git
    dest=~/.emacs.d
    accept_hostkey=yes
    recursive=yes
  when: not emacs_config_path.stat.exists
