---
- name: check if oh my zsh already installed
  sudo: yes
  sudo_user: "{{remote_user}}"
  stat: path=~/.oh-my-zsh
  register: omz_path
  changed_when: False

- name: clone oh my zsh
  sudo: yes
  sudo_user: "{{remote_user}}"
  git: >-
    repo=git@github.com:robbyrussell/oh-my-zsh.git
    dest=~/.oh-my-zsh
    accept_hostkey=yes
  when: not omz_path.stat.exists

- name: symlink .zshrc
  sudo: yes
  sudo_user: "{{remote_user}}"
  file: src=~/dotfiles/.zshrc dest=~/.zshrc state=link

- name: change user default shell
  sudo: yes
  user: name={{remote_user}} shell=/usr/bin/zsh
